# Generated by Django 4.0.5 on 2022-07-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_systems', '0004_alter_userprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
