# Generated by Django 4.0.5 on 2022-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_systems', '0006_alter_userprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
