# Generated by Django 4.0.5 on 2022-07-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('div_systems', '0008_alter_userprofile_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default='1995-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(default='EG', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='ahmed', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='said', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='01158626091', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
